apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  requirements:
    - key: "node.kubernetes.io/instance-type"
      operator: In
      values: ["t3.medium"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: "100"
      memory: "200Gi"
  provider:
    instanceProfile: "KarpenterNodeInstanceProfile"
    securityGroupSelector:
      karpenter.sh/discovery: wiary
    subnetSelector:
      karpenter.sh/discovery: wiary
  ttlSecondsAfterEmpty: 30 