apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: karpenter
spec:
  containers:
  - name: test
    image: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
  nodeSelector:
    karpenter.sh/provisioner-name: default 