controller:
  clusterName: ${KARPENTER_CLUSTER_NAME}
  clusterEndpoint: ${KARPENTER_CLUSTER_ENDPOINT}
  aws:
    defaultInstanceProfile: ${KARPENTER_INSTANCE_PROFILE}
    useServiceLinkedRole: ${KARPENTER_SERVICE_LINKED_ROLE}
  podAnnotations:
    iam.amazonaws.com/role: ${KARPENTER_NODE_ROLE}
  env:
    - name: AWS_REGION
      value: ${KARPENTER_AWS_REGION}
    - name: AWS_DEFAULT_REGION
      value: ${KARPENTER_AWS_DEFAULT_REGION}
    - name: CLUSTER_NAME
      value: ${KARPENTER_CLUSTER_NAME}
    - name: CLUSTER_ENDPOINT
      value: ${KARPENTER_CLUSTER_ENDPOINT} 