name: Deploy Karpenter and HPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  KUBECONFIG: ${{ secrets.KUBECONFIG }}
  AWS_REGION: us-west-2  # 변경 필요
  CLUSTER_NAME: wiray  # 변경 필요
  KARPENTER_VERSION: 0.16.3

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Install Karpenter
      run: |
        helm repo add karpenter https://charts.karpenter.sh
        helm repo update
        helm install karpenter karpenter/karpenter \
          --namespace karpenter \
          --create-namespace \
          --version ${{ env.KARPENTER_VERSION }} \
          --set serviceAccount.annotations."eks\.amazonaws\.com/role-arn"=${{ secrets.KARPENTER_IAM_ROLE_ARN }}

    - name: Apply Provisioner
      run: |
        kubectl apply -f provisioner/default-provisioner.yaml -n karpenter

    - name: Apply HPA
      run: |
        kubectl apply -f hpa/ -n karpenter

    - name: Update ASG
      run: |
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
          --min-size 1 \
          --max-size 1 \
          --desired-capacity 1