name: Deploy Karpenter and HPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-west-2
  CLUSTER_NAME: wiary
  KARPENTER_VERSION: 0.16.3
  KUBECONFIG: /home/runner/.kube/config

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Setup kubeconfig
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
      run: |
        echo "Creating .kube directory..."
        mkdir -p /home/runner/.kube
        echo "Updating kubeconfig with AWS CLI..."
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        echo "Setting kubeconfig permissions..."
        chmod 600 ${{ env.KUBECONFIG }}
        echo "Verifying kubeconfig file exists..."
        ls -la ${{ env.KUBECONFIG }}
        echo "Testing AWS credentials..."
        aws sts get-caller-identity
        echo "Testing kubectl access..."
        kubectl get nodes

    - name: Install Karpenter
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
      run: |
        helm repo add karpenter https://charts.karpenter.sh
        helm repo update
        helm install karpenter karpenter/karpenter \
          --namespace karpenter \
          --create-namespace \
          --version ${{ env.KARPENTER_VERSION }} \
          --set controller.clusterName=${{ env.CLUSTER_NAME }} \
          --set controller.clusterEndpoint=$(aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --query "cluster.endpoint" --output text) \
          --set controller.aws.defaultInstanceProfile=KarpenterNodeInstanceProfile \
          --set controller.aws.useServiceLinkedRole=true \
          --set controller.podAnnotations."iam\.amazonaws\.com/role=KarpenterNodeInstanceRole" \
          --set controller.env[0].name=AWS_REGION \
          --set controller.env[0].value=${{ env.AWS_REGION }} \
          --set controller.env[1].name=AWS_DEFAULT_REGION \
          --set controller.env[1].value=${{ env.AWS_REGION }} \
          --set controller.env[2].name=CLUSTER_NAME \
          --set controller.env[2].value=${{ env.CLUSTER_NAME }} \
          --set controller.env[3].name=CLUSTER_ENDPOINT \
          --set controller.env[3].value=$(aws eks describe-cluster --name ${{ env.CLUSTER_NAME }} --query "cluster.endpoint" --output text)

    - name: Apply Provisioner
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
      run: |
        kubectl apply -f provisioner/default-provisioner.yaml -n karpenter

    - name: Apply HPA
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        KUBECONFIG: ${{ env.KUBECONFIG }}
      run: |
        kubectl apply -f hpa/ -n karpenter

    - name: Update ASG
      run: |
        aws autoscaling update-auto-scaling-group \
          --auto-scaling-group-name ${{ secrets.ASG_NAME }} \
          --min-size 1 \
          --max-size 1 \
          --desired-capacity 1